import type { Metadata } from "next";
import {Afacad} from 'next/font/google'
import "./globals.css";
import AdminLayout from "@/components/sidebar/Admin-layout";



const afacad =Afacad({
  subsets:['latin'],
  display:'swap'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={afacad.className} >
      <AdminLayout>
        {children}
        </AdminLayout>
      </body>
    </html>
  );
}
